// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// La CLI Prisma ne charge pas .env.local automatiquement (contrairement à
// Next.js) : on le charge explicitement pour DATABASE_URL/DIRECT_URL.
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations utilisent la connexion directe (port 5432, mode session) :
    // le pooler transaction-mode (DATABASE_URL, port 6543) ne supporte pas
    // les prepared statements nécessaires aux migrations. Le client Prisma
    // au runtime (src/lib/prisma.ts) utilise DATABASE_URL via l'adaptateur
    // node-postgres, indépendamment de ce fichier.
    url: process.env["DIRECT_URL"],
  },
});
